version: '3.12'

services:
  django: 
    image: django.docker:0.0.1
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db   

  db: 
    image: postgres:17
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: hello123
      POSTGRES_DB: default