# Generated by Django 5.2.3 on 2025-07-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('datebought', models.CharField(max_length=10)),
                ('datesold', models.CharField(max_length=10)),
                ('amountbought', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
